### ISSUE TITLE
Compatibility with Events Tickets 4.11.0.1 / Events Tickets Plus 4.11.0.2

### ISSUE THREAD

**Issue by oliverchambers** [kathyisawesome/wc-nyp-event-tickets#1]
Since updating to the latest version of events tickets the NYM field does not appear on the new ticket field

**Comment by helgatheviking** [comment]
Thanks for reporting this. This plugin doesn't receive priority support, but I will check on it as soon as I'm able.

**Comment by oliverchambers** [comment]
Thanks HelgatheViking! We’re a non profit and this plugin is really useful. 🤞🏻For an update soon 😊

**Comment by helgatheviking** [comment]
Sorry,  I've looked at this all morning and whatever new thing they've done is very complex. It would almost assuredly need to be a paid project to continue.

**Comment by Supaiku** [comment]
I'm into this too... perhaps others would also like this functionality and we could split the cost? :)

**Comment by helgatheviking** [comment]
ref: https://docs.theeventscalendar.com/reference/hooks/tribe_template_htmlhook_name/

```
function test_ticket(  $html, $file, $name, $template )
 {
 return 'Kathy loves tacos';
}
add_filter( 'tribe_template_html:tickets/blocks/tickets/extra-price', 'test_ticket', 10, 4);
```

more ref: https://wordpress.org/support/topic/conditionally-switching-the-blocks-tickets-extra-price-template/

**Comment by helgatheviking** [comment]
@oliverchambers @Supaiku 

Hi everyone.... After another day of tinkering on this... I think there is some progress that might be worth testing.

The ticket can be set as NYP in the tickets admin interface... and the price input will display on the front end event page:
![image](https://user-images.githubusercontent.com/507025/98979830-12fce980-24d9-11eb-8a22-b9a48d07c0e8.png)

Please give [this branch](https://github.com/kathyisawesome/wc-nyp-event-tickets/tree/issues/1-events-411) a test run and let me know what you find. Keep in mind this is preliminary and should be thoroughly tested before being used in production. You've probably already realized this :) but this project isn't top priority for me and proceeds very much at a "when I have time" pace.

Hope the new code works for y'all!

**Comment by Supaiku** [comment]
Sweet, I'll try it out on your dev site!

**Comment by Supaiku** [comment]
Got it installed :)

Seems to work as shown there on our site too!

Any particular things you think we should test?
Happy to help with the thoroughly testing part if that's  way we can contribute! :)

We currently have a short list of tests we do before rolling out plugin updates, and have a rediculous number of plugins on our site, including WPML, WooCommerce Membership, Subscriptions, Events, and more so... if it doesn't have conflicts on our site... well that's a good sign anyhow.

**Comment by helgatheviking** [comment]
@Supaiku I think testing the creation, display, and add to cart functions of a name your price ticket is super helpful. and great to hear so far there are no conflicts. 

I was feeling like I may have jumped the gun a bit since I tried this on another site and the NYP ticket isn't displaying on the front-end there. but it's the weekend so i'm not looking in to it right now.

**Comment by Supaiku** [comment]
It's working on ours with: 

Creation 

Display and cart 

I didn't try checking out all the way but I will 


I can send a link if you want to take a look at it in action for any reason 


Sent from Workspace ONE Boxer 


On Nov 15, 2020 10:40 AM, Kathy <notifications@github.com> wrote: 

@Supaiku I think testing the creation, display, and add to cart functions of a name your price ticket is super helpful. and great to hear so far there are no conflicts.

I was feeling like I may have jumped the gun a bit since I tried this on another site and the NYP ticket isn't displaying on the front-end there. but it's the weekend so i'm not looking in to it right now.

**Comment by helgatheviking** [comment]
My name your price ticket wasn't displaying because it had last years date! Working for you, and working for me, I'm going to go ahead and merge it. It will still fall under non-priority support, but it's great to have it working again!

**Comment by Supaiku** [comment]
That's wonderful! Thanks for giving it some attention!!! :) 


Excited to let our training person know! :) 


On Nov 16, 2020 7:04 PM, Kathy <notifications@github.com> wrote: 

My name your price ticket wasn't displaying because it had last years date! Working for you, and working for me, I'm going to go ahead and merge it. It will still fall under non-priority support, but it's great to have it working again!

**Comment by helgatheviking** [comment]
there's a little tweak I need to ship to NYP in the next version to make the validation script a little smoother.... and chatting with the Events Tickets team about another little validation UX thing, but it appears functional!
