### ISSUE TITLE
Missing Suggested Price in ticket display

### ISSUE THREAD

**Issue by hp7** [kathyisawesome/wc-nyp-event-tickets#4]
Hello I tested your latest 2.0.0 Beta 1 but doesn't work with
	WordPress 5.5.3
	Events Calendar PRO 5.1.6
	Event Tickets Plus 5.0.1
	WOOCommerce 4.7.0

Any intension/interest in making this a subscription plugin?

**Comment by helgatheviking** [comment]
Can you provide more detail? "Doesn't work" is very vague. Can you describe exactly what you were doing and what happened? Screenshots are helpful too. Somewhere around Events 4.11 the original code stopped working after they made some big changes to their template.

I merged some new stuff into the `master` just last night to deal with compatibility with Events 5. See #1. Make sure you have the latest master... I don't think I version bumped to 1.0-rc1 yet.  

There's one tweak that I need to ship out in NYP to make front-end validation better.. I'm trying to do that today.

Keep in mind this plugin does not receive priority support and I'm not sure when I'll be able to work on it again. I hadn't really thought about making this a subscription plugin, tbh. There's clearly _some_ demand, but it's also difficult for me to work with Events since I'm not that familiar with it.

**Comment by hp7** [comment]
Thank you for looking at this and working on it! 
![Screen Shot 2020-11-17 at 10 29 09 AM](https://user-images.githubusercontent.com/786681/99410340-5d5add80-28c0-11eb-9d3a-e99d0c09dc96.jpg)

Not sure how you prefer I submit the issues, but I will send them individually.

**Issue 1**
Suggested Price doesn't show up in frontend
